apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: trend

  template:
    metadata:
      labels:
        app: trend

    spec:
      containers:
        - name: trend-container
          image: jwalapj02/app:IMAGE_TAG

          ports:
            - containerPort: 80   # ✅ FIXED

          imagePullPolicy: IfNotPresent   # ✅ faster

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
