apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2

  selector:
    matchLabels:
      app: trend   # MUST match below

  template:
    metadata:
      labels:
        app: trend   # MUST match above

    spec:
      containers:
      - name: trend-container
        image: jwalapj02/app:1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
